# Generated by Django 2.0.2 on 2018-02-12 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 9, 56, 56, 606987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 9, 56, 56, 607522, tzinfo=utc)),
        ),
    ]
