# Generated by Django 2.0.2 on 2018-02-12 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180212_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 10, 52, 14, 176546, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 10, 52, 14, 177432, tzinfo=utc)),
        ),
    ]
