# Generated by Django 2.0.2 on 2018-02-12 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180212_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 11, 40, 21, 806888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 11, 40, 21, 807437, tzinfo=utc)),
        ),
    ]
